language: python

python: 
  - "2.7"

branches:
  only:
    - milestone-1-kedar

sudo: false

install: true

before_script:
  - pip install virtualenv
  - cd FlaskModule
  - virtualenv venv
  - . venv/bin/activate
  - pip install nose
  - pip install Flask

script: nosetests

before_deploy:
  - cd ..
  - zip -r SGA_NPComplete_Application.zip FlaskModule || true
  - mkdir -p "dpl_cd_upload"
  - mv SGA_NPComplete_Application.zip dpl_cd_upload/SGA_NPComplete_Application.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: sga-teamnpcomplete
    local_dir: dpl_cd_upload
    region: us-west-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      branch: milestone-1-kedar

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: sga-teamnpcomplete
    key: SGA_NPComplete_Application.zip
    bundle_type: zip
    application: TeamNpComplete
    deployment_group: TeamNpComplete
    region: us-west-2
    on:
      branch: milestone-1-kedar

after_deploy:
  - echo "Deployment done"

notifications:
  email:
    - kgundlup@umail.iu.edu