language: python
branches:
  only:
    - milestone-1-kedar
notifications:
  email:
    - kgundlup@umail.iu.edu

sudo: false
install:
  - pip install virtualenv
  - cd FlaskModule
  - virtualenv venv
  - . venv/bin/activate
  - pip install Flask
script: 
  - export FLASK_APP=hello.py
  - flask run --host=0.0.0.0