language: python

python: 
  - "2.7"

branches:
  only:
    - milestone-3

sudo: required

services:
  - docker

install:
  - docker build -t kedargn/forecastrun .
  - docker ps -a
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push kedargn/forecastrun

before_script:
  - cd Forecast
  - pip install requests
  - pip install nose
  - pip install Flask
  - cd ..


script: nosetests

before_deploy:
  - zip -r SGA_Forecast.zip scripts appspec.yml || true
  - mkdir -p "dpl_cd_upload"
  - mv SGA_Forecast.zip dpl_cd_upload/SGA_Forecast.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: sga-teamnpcomplete
    local_dir: dpl_cd_upload
    region: us-west-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      branch: milestone-3

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: sga-teamnpcomplete
    key: SGA_Forecast.zip
    bundle_type: zip
    application: TeamNPComplete
    deployment_group: TeamNPComplete
    region: us-west-2
    on:
      branch: milestone-3

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY_TEST # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY_TEST
    bucket: sga-teamnpcomplete
    key: SGA_Forecast.zip
    bundle_type: zip
    application: TeamNPCompleteTest
    deployment_group: TeamNPCompleteTest
    region: us-west-2
    on:
      branch: milestone-3

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: sga-teamnpcomplete
    key: SGA_Forecast.zip
    bundle_type: zip
    application: TeamNpComplete3
    deployment_group: TeamNpComplete3
    region: us-east-2
    on:
      branch: milestone-3
