language: python
branches:
  only:
    - milestone-1-kedar
notifications:
  email:
    - kgundlup@umail.iu.edu

sudo: false
install: true
script: 
  - cd FlaskModule
  - virtualvenv venv
  - . vnev/bin/activate
  - pip install Flask
  - export FLASK_APP=hello.py
  - flask run 